export interface CharacterBio {
  name: string;
  nameGu: string;
  nameHi: string;
  role: string;
  bio: string;
}

export const characterBios: Record<string, CharacterBio> = {
  // Vachanamrut characters
  'Bhagwan Swaminarayan': {
    name: 'Bhagwan Swaminarayan',
    nameGu: 'ભગવાન સ્વામિનારાયણ',
    nameHi: 'भगवान स्वामीनारायण',
    role: 'Supreme Being / Teacher',
    bio: 'Bhagwan Swaminarayan (1781–1830) is the central figure of the Swaminarayan Sampraday. Born as Ghanshyam in Chhapaiya, he renounced the world at age 11, traveled across India, and established a spiritual tradition emphasizing dharma, knowledge, detachment, and devotion. The Vachanamrut is a compilation of his 262 spiritual discourses.',
  },
  'Muktanand Swami': {
    name: 'Muktanand Swami',
    nameGu: 'મુક્તાનંદ સ્વામી',
    nameHi: 'मुक्तानंद स्वामी',
    role: 'Senior Saint / Questioner',
    bio: 'Muktanand Swami was one of the foremost paramhansas (senior saints) and a prolific poet-saint in the Swaminarayan Sampraday. He frequently posed profound philosophical questions to Bhagwan Swaminarayan, which form the basis of many Vachanamrut discourses.',
  },
  'Gopalanand Swami': {
    name: 'Gopalanand Swami',
    nameGu: 'ગોપાળાનંદ સ્વામી',
    nameHi: 'गोपालानंद स्वामी',
    role: 'Senior Saint / Scholar',
    bio: 'Gopalanand Swami was a highly learned paramhansa known for his deep understanding of Vedantic philosophy. He was instrumental in the compilation and preservation of the Vachanamrut texts.',
  },
  'Nityanand Swami': {
    name: 'Nityanand Swami',
    nameGu: 'નિત્યાનંદ સ્વામી',
    nameHi: 'नित्यानंद स्वामी',
    role: 'Senior Saint / Compiler',
    bio: 'Nityanand Swami was one of the paramhansas who helped compile the Vachanamrut. He was deeply devoted and is known for his scholarly contributions to the Swaminarayan literary tradition.',
  },
  'Shukanand Swami': {
    name: 'Shukanand Swami',
    nameGu: 'શુકાનંદ સ્વામી',
    nameHi: 'शुकानंद स्वामी',
    role: 'Senior Saint',
    bio: 'Shukanand Swami was a devoted paramhansa who participated in many of the philosophical discussions recorded in the Vachanamrut.',
  },
  'Brahmanand Swami': {
    name: 'Brahmanand Swami',
    nameGu: 'બ્રહ્માનંદ સ્વામી',
    nameHi: 'ब्रह्मानंद स्वामी',
    role: 'Poet-Saint',
    bio: 'Brahmanand Swami was a renowned poet-saint in the Swaminarayan tradition, celebrated for his devotional poetry and hymns. He often asked questions in the assemblies that led to important teachings.',
  },

  // Bhagavad Gita characters
  'Krishna': {
    name: 'Krishna',
    nameGu: 'કૃષ્ણ',
    nameHi: 'कृष्ण',
    role: 'Supreme Being / Charioteer',
    bio: 'Lord Krishna is the Supreme Personality of Godhead who serves as Arjuna\'s charioteer on the battlefield of Kurukshetra. He delivers the Bhagavad Gita\'s teaching — a discourse covering dharma, yoga, devotion, and the nature of reality — to resolve Arjuna\'s moral crisis about fighting his own relatives.',
  },
  'Arjuna': {
    name: 'Arjuna',
    nameGu: 'અર્જુન',
    nameHi: 'अर्जुन',
    role: 'Warrior Prince / Student',
    bio: 'Arjuna is the third Pandava prince and one of the greatest warriors of his age. On the battlefield, he faces a moral crisis at the prospect of fighting his own kinsmen, teachers, and elders. His questions and doubts prompt Krishna\'s profound teachings in the Gita.',
  },
  'Sanjaya': {
    name: 'Sanjaya',
    nameGu: 'સંજય',
    nameHi: 'संजय',
    role: 'Narrator / Divine Seer',
    bio: 'Sanjaya is the charioteer and minister of the blind king Dhritarashtra. Granted divine vision by the sage Vyasa, he narrates the events of the Kurukshetra war, including the Bhagavad Gita dialogue, to the king in real-time.',
  },
  'Dhritarashtra': {
    name: 'Dhritarashtra',
    nameGu: 'ધૃતરાષ્ટ્ર',
    nameHi: 'धृतराष्ट्र',
    role: 'Blind King',
    bio: 'Dhritarashtra is the blind king of the Kuru dynasty and father of the Kauravas. Unable to see the battlefield, he relies on Sanjaya\'s narration. His opening question in the Gita reflects his anxiety about the outcome of the war.',
  },

  // Upanishad characters
  'Narrator': {
    name: 'Narrator',
    nameGu: 'વર્ણનકાર',
    nameHi: 'वर्णनकार',
    role: 'Commentary',
    bio: 'The narrative voice provides context, commentary, and philosophical reflection on the Upanishadic teachings, helping the reader understand the deeper significance of each passage.',
  },
  'The Teacher': {
    name: 'The Teacher',
    nameGu: 'ગુરુ',
    nameHi: 'गुरु',
    role: 'Spiritual Guide',
    bio: 'The unnamed teacher in the Upanishads represents the guru tradition — the lineage of spiritual masters who transmit sacred knowledge from generation to generation through direct instruction.',
  },
  'The Sage': {
    name: 'The Sage',
    nameGu: 'ઋષિ',
    nameHi: 'ऋषि',
    role: 'Enlightened Seer',
    bio: 'The sage (rishi) is one who has realized the truth of Brahman through meditation and austerity. In the Upanishads, sages serve as the primary teachers, sharing their direct experience of ultimate reality.',
  },
  'Nachiketa': {
    name: 'Nachiketa',
    nameGu: 'નચિકેતા',
    nameHi: 'नचिकेता',
    role: 'Young Seeker',
    bio: 'Nachiketa is the fearless young boy in the Katha Upanishad who journeys to the abode of Yama, the Lord of Death. Despite being offered every worldly pleasure, he insists on learning the secret of what lies beyond death — becoming a symbol of spiritual determination.',
  },
  'Yama': {
    name: 'Yama',
    nameGu: 'યમ',
    nameHi: 'यम',
    role: 'Lord of Death / Teacher',
    bio: 'Yama (Dharmaraja) is the Lord of Death and cosmic judge in Hindu mythology. In the Katha Upanishad, he serves as Nachiketa\'s teacher, reluctantly revealing the supreme knowledge of the Self after testing the boy\'s resolve.',
  },
  'Vajashravasa': {
    name: 'Vajashravasa',
    nameGu: 'વાજશ્રવસ',
    nameHi: 'वाजश्रवस',
    role: 'Father of Nachiketa',
    bio: 'Vajashravasa is Nachiketa\'s father who performs a sacrifice but gives away only old, barren cows. His son Nachiketa, troubled by this hollow ritual, asks to be given to Death, setting the Katha Upanishad story in motion.',
  },
  'Pippalada': {
    name: 'Pippalada',
    nameGu: 'પિપ્પલાદ',
    nameHi: 'पिप्पलाद',
    role: 'Sage / Teacher',
    bio: 'Sage Pippalada is the central teacher of the Prashna Upanishad. Six seekers approach him with fundamental questions about creation, prana, consciousness, dreams, and meditation. He answers each with clarity and depth.',
  },
  'Angiras': {
    name: 'Angiras',
    nameGu: 'અંગિરસ',
    nameHi: 'अंगिरस',
    role: 'Sage / Teacher',
    bio: 'Angiras is the sage who teaches in the Mundaka Upanishad. He distinguishes between higher knowledge (knowledge of Brahman) and lower knowledge (ritualistic learning), guiding the seeker Shaunaka toward direct realization.',
  },
  'Shaunaka': {
    name: 'Shaunaka',
    nameGu: 'શૌનક',
    nameHi: 'शौनक',
    role: 'Seeker / Student',
    bio: 'Shaunaka is the householder-sage who approaches Angiras in the Mundaka Upanishad with the great question: "What is that, by knowing which, everything becomes known?" His question sets the stage for the teaching on Brahman.',
  },
  'Uddalaka': {
    name: 'Uddalaka',
    nameGu: 'ઉદ્દાલક',
    nameHi: 'उद्दालक',
    role: 'Father / Teacher',
    bio: 'Uddalaka Aruni is the wise father-teacher in the Chandogya Upanishad who teaches his son Shvetaketu the nature of Brahman through vivid analogies — salt in water, the banyan seed, rivers merging in the ocean — each culminating in the great declaration "Tat tvam asi" (You are That).',
  },
  'Shvetaketu': {
    name: 'Shvetaketu',
    nameGu: 'શ્વેતકેતુ',
    nameHi: 'श्वेतकेतु',
    role: 'Son / Student',
    bio: 'Shvetaketu is Uddalaka\'s son who returns from twelve years of Vedic study proud but lacking knowledge of the Self. His father\'s teaching of "Tat tvam asi" in the Chandogya Upanishad becomes one of the most celebrated passages in all of Hindu philosophy.',
  },
  'Narada': {
    name: 'Narada',
    nameGu: 'નારદ',
    nameHi: 'नारद',
    role: 'Divine Sage / Seeker',
    bio: 'Narada is the celestial sage and wandering devotee who knows all the Vedas and sciences yet confesses to Sanatkumara: "I know all this, but I do not know the Self." His humility and seeking lead to the profound teaching on the Infinite (Bhuma) in the Chandogya Upanishad.',
  },
  'Sanatkumara': {
    name: 'Sanatkumara',
    nameGu: 'સનત્કુમાર',
    nameHi: 'सनत्कुमार',
    role: 'Eternal Youth / Teacher',
    bio: 'Sanatkumara is one of the four mind-born sons of Brahma, eternally young and wise. In the Chandogya Upanishad, he guides Narada through ascending levels of meditation — from name to speech to mind to will — until reaching the Infinite (Bhuma), which alone is bliss.',
  },
  'Prajapati': {
    name: 'Prajapati',
    nameGu: 'પ્રજાપતિ',
    nameHi: 'प्रजापति',
    role: 'Creator / Teacher',
    bio: 'Prajapati (the Creator) teaches both the gods (Indra) and the demons (Virochana) about the nature of the Self in the Chandogya Upanishad. His progressive teaching over 101 years reveals the Self beyond body, dreams, and deep sleep.',
  },
  'Indra': {
    name: 'Indra',
    nameGu: 'ઇન્દ્ર',
    nameHi: 'इन्द्र',
    role: 'King of Gods / Student',
    bio: 'Indra, the king of the gods, is a student of Prajapati in the Chandogya Upanishad. Unlike Virochana who accepts the first answer, Indra\'s persistent dissatisfaction drives him back three times over 101 years until he receives the complete teaching on the true Self.',
  },
  'Virochana': {
    name: 'Virochana',
    nameGu: 'વિરોચન',
    nameHi: 'विरोचन',
    role: 'King of Demons',
    bio: 'Virochana is the demon king who studies alongside Indra under Prajapati. He hastily accepts the body-reflection as the Self and returns satisfied — representing those who mistake the physical for the spiritual.',
  },
  'Yajnavalkya': {
    name: 'Yajnavalkya',
    nameGu: 'યાજ્ઞવલ્ક્ય',
    nameHi: 'याज्ञवल्क्य',
    role: 'Supreme Sage',
    bio: 'Yajnavalkya is the towering philosophical figure of the Brihadaranyaka Upanishad — bold, brilliant, and uncompromising. He defeats all challengers in King Janaka\'s court, teaches his wife Maitreyi the nature of the Self, and articulates the honey doctrine of universal interconnection.',
  },
  'Maitreyi': {
    name: 'Maitreyi',
    nameGu: 'મૈત્રેયી',
    nameHi: 'मैत्रेयी',
    role: 'Wife / Philosopher',
    bio: 'Maitreyi is Yajnavalkya\'s wife and one of the great women philosophers of ancient India. When offered all her husband\'s wealth before his renunciation, she asks: "Will this make me immortal?" Her refusal of wealth in favor of Self-knowledge is a defining moment in the Upanishads.',
  },
  'Gargi': {
    name: 'Gargi',
    nameGu: 'ગાર્ગી',
    nameHi: 'गार्गी',
    role: 'Woman Philosopher',
    bio: 'Gargi Vachaknavi is a fearless woman philosopher who challenges Yajnavalkya in the public debate at King Janaka\'s court. She presses him with relentless questioning about the ultimate warp and weft of reality until he describes the Imperishable (Akshara) upon which space itself is woven.',
  },
  'King Janaka': {
    name: 'King Janaka',
    nameGu: 'રાજા જનક',
    nameHi: 'राजा जनक',
    role: 'Philosopher King',
    bio: 'King Janaka of Videha is the philosopher-king who hosts the great debate in the Brihadaranyaka Upanishad and becomes Yajnavalkya\'s devoted student. He represents the ideal of a ruler who seeks spiritual wisdom while fulfilling worldly duties.',
  },
  'Vidagdha Shakalya': {
    name: 'Vidagdha Shakalya',
    nameGu: 'વિદગ્ધ શાકલ્ય',
    nameHi: 'विदग्ध शाकल्य',
    role: 'Challenger / Scholar',
    bio: 'Vidagdha Shakalya is the scholar who challenges Yajnavalkya in King Janaka\'s court with the famous question "How many gods are there?" Yajnavalkya\'s answer progressively reduces from 3,306 to one, revealing that all gods are manifestations of the one Brahman.',
  },
  'Kabandhi': {
    name: 'Kabandhi',
    nameGu: 'કબંધી',
    nameHi: 'कबन्धी',
    role: 'Seeker',
    bio: 'Kabandhi Katyayana is one of the six seekers in the Prashna Upanishad. He asks Pippalada the first question: "From what are all creatures born?"',
  },
  'Bhargava': {
    name: 'Bhargava',
    nameGu: 'ભાર્ગવ',
    nameHi: 'भार्गव',
    role: 'Seeker',
    bio: 'Bhargava Vaidarbhi is one of the six seekers in the Prashna Upanishad. He asks: "How many powers support a being, and which is the greatest?"',
  },
  'Kausalya': {
    name: 'Kausalya',
    nameGu: 'કૌસલ્ય',
    nameHi: 'कौसल्य',
    role: 'Seeker',
    bio: 'Kausalya Ashvalayana is one of the six seekers in the Prashna Upanishad. He asks: "Where does prana come from? How does it enter the body?"',
  },
  'Sauryayani': {
    name: 'Sauryayani',
    nameGu: 'સૌર્યયાણી',
    nameHi: 'सौर्ययाणी',
    role: 'Seeker',
    bio: 'Sauryayani Gargya is one of the six seekers in the Prashna Upanishad. He asks: "What sleeps in a person and what stays awake? Which faculty sees dreams?"',
  },
  'Satyakama': {
    name: 'Satyakama',
    nameGu: 'સત્યકામ',
    nameHi: 'सत्यकाम',
    role: 'Seeker',
    bio: 'Satyakama Shaibya is one of the six seekers in the Prashna Upanishad. He asks about the fruit of meditating on Om. Also appears in the Chandogya Upanishad as Satyakama Jabala, whose truthfulness about his unknown parentage earns him acceptance as a student.',
  },
  'Sukesha': {
    name: 'Sukesha',
    nameGu: 'સુકેશ',
    nameHi: 'सुकेश',
    role: 'Seeker',
    bio: 'Sukesha Bharadvaja is one of the six seekers in the Prashna Upanishad. He asks the final and most profound question: "Where is the Purusha with sixteen parts?"',
  },
  'Uma': {
    name: 'Uma',
    nameGu: 'ઉમા',
    nameHi: 'उमा',
    role: 'Divine Mother / Revealer',
    bio: 'Uma Haimavati (daughter of the Himalayas) appears in the Kena Upanishad when the gods fail to understand Brahman. She reveals to Indra that the mysterious being who humbled the gods was Brahman itself — representing the feminine aspect of divine wisdom.',
  },
  'The Student': {
    name: 'The Student',
    nameGu: 'શિષ્ય',
    nameHi: 'शिष्य',
    role: 'Spiritual Seeker',
    bio: 'The unnamed student represents the earnest seeker who approaches a teacher with humility and genuine desire for knowledge. In the Upanishadic tradition, the student-teacher relationship is sacred — the word "Upanishad" itself means "sitting near" the guru.',
  },
  'Student': {
    name: 'Student',
    nameGu: 'શિષ્ય',
    nameHi: 'शिष्य',
    role: 'Spiritual Seeker',
    bio: 'The student represents the earnest seeker who approaches a teacher with humility and genuine desire for knowledge of Brahman.',
  },
  'The Rishi': {
    name: 'The Rishi',
    nameGu: 'ઋષિ',
    nameHi: 'ऋषि',
    role: 'Enlightened Seer',
    bio: 'The Rishi is a seer of truth who has realized Brahman through meditation and austerity. Rishis are the original receivers of Vedic knowledge, transmitting what they "saw" in deep states of consciousness.',
  },
  'Satyakama Jabala': {
    name: 'Satyakama Jabala',
    nameGu: 'સત્યકામ જાબાલ',
    nameHi: 'सत्यकाम जाबाल',
    role: 'Truthful Seeker',
    bio: 'Satyakama Jabala is a boy of unknown parentage in the Chandogya Upanishad. When asked his lineage, he honestly admits he does not know his father. His truthfulness so impresses the guru Gautama that he is accepted as a student — demonstrating that truth, not birth, qualifies one for spiritual knowledge.',
  },
  'Gautama Haridrumata': {
    name: 'Gautama Haridrumata',
    nameGu: 'ગૌતમ હારિદ્રુમત',
    nameHi: 'गौतम हारिद्रुमत',
    role: 'Teacher / Guru',
    bio: 'Gautama Haridrumata is the sage who accepts Satyakama Jabala as his student in the Chandogya Upanishad. Recognizing the boy\'s truthfulness as proof of his noble character, he initiates him into the study of Brahman.',
  },
  'Ushasta': {
    name: 'Ushasta',
    nameGu: 'ઉષસ્ત',
    nameHi: 'उषस्त',
    role: 'Philosopher / Questioner',
    bio: 'Ushasta Chakrayana is one of the learned sages who questions Yajnavalkya in King Janaka\'s court in the Brihadaranyaka Upanishad. He asks: "What is that Brahman which is directly perceived — the Self within all?"',
  },
  'Kahola': {
    name: 'Kahola',
    nameGu: 'કહોલ',
    nameHi: 'कहोल',
    role: 'Philosopher / Questioner',
    bio: 'Kahola Kaushitakeya is one of the Brahmin scholars who participates in the philosophical debate at King Janaka\'s court in the Brihadaranyaka Upanishad.',
  },
};

export function getCharacterBio(speakerName: string): CharacterBio | undefined {
  return characterBios[speakerName];
}
