import type { Section } from '../types';

export const gitaChapters: Section[] = [
  {
    index: 1,
    name: 'Arjuna Vishada Yoga',
    nameGu: 'અર્જુન વિષાદ યોગ',
    nameHi: 'अर्जुन विषाद योग',
    totalItems: 5,
    range: [1, 5],
  },
  {
    index: 2,
    name: 'Sankhya Yoga',
    nameGu: 'સાંખ્ય યોગ',
    nameHi: 'सांख्य योग',
    totalItems: 7,
    range: [6, 12],
  },
  {
    index: 3,
    name: 'Karma Yoga',
    nameGu: 'કર્મ યોગ',
    nameHi: 'कर्म योग',
    totalItems: 4,
    range: [13, 16],
  },
  {
    index: 4,
    name: 'Jnana Karma Sanyasa Yoga',
    nameGu: 'જ્ઞાન કર્મ સંન્યાસ યોગ',
    nameHi: 'ज्ञान कर्म संन्यास योग',
    totalItems: 4,
    range: [17, 20],
  },
  {
    index: 5,
    name: 'Karma Sanyasa Yoga',
    nameGu: 'કર્મ સંન્યાસ યોગ',
    nameHi: 'कर्म संन्यास योग',
    totalItems: 3,
    range: [21, 23],
  },
  {
    index: 6,
    name: 'Dhyana Yoga',
    nameGu: 'ધ્યાન યોગ',
    nameHi: 'ध्यान योग',
    totalItems: 5,
    range: [24, 28],
  },
  {
    index: 7,
    name: 'Jnana Vijnana Yoga',
    nameGu: 'જ્ઞાન વિજ્ઞાન યોગ',
    nameHi: 'ज्ञान विज्ञान योग',
    totalItems: 3,
    range: [29, 31],
  },
  {
    index: 8,
    name: 'Akshara Brahma Yoga',
    nameGu: 'અક્ષર બ્રહ્મ યોગ',
    nameHi: 'अक्षर ब्रह्म योग',
    totalItems: 3,
    range: [32, 34],
  },
  {
    index: 9,
    name: 'Raja Vidya Raja Guhya Yoga',
    nameGu: 'રાજવિદ્યા રાજગુહ્ય યોગ',
    nameHi: 'राजविद्या राजगुह्य योग',
    totalItems: 3,
    range: [35, 37],
  },
  {
    index: 10,
    name: 'Vibhuti Yoga',
    nameGu: 'વિભૂતિ યોગ',
    nameHi: 'विभूति योग',
    totalItems: 4,
    range: [38, 41],
  },
  {
    index: 11,
    name: 'Vishwarupa Darshana Yoga',
    nameGu: 'વિશ્વરૂપ દર્શન યોગ',
    nameHi: 'विश्वरूप दर्शन योग',
    totalItems: 6,
    range: [42, 47],
  },
  {
    index: 12,
    name: 'Bhakti Yoga',
    nameGu: 'ભક્તિ યોગ',
    nameHi: 'भक्ति योग',
    totalItems: 2,
    range: [48, 49],
  },
  {
    index: 13,
    name: 'Kshetra Kshetrajna Vibhaga Yoga',
    nameGu: 'ક્ષેત્ર ક્ષેત્રજ્ઞ વિભાગ યોગ',
    nameHi: 'क्षेत्र क्षेत्रज्ञ विभाग योग',
    totalItems: 4,
    range: [50, 53],
  },
  {
    index: 14,
    name: 'Gunatraya Vibhaga Yoga',
    nameGu: 'ગુણત્રય વિભાગ યોગ',
    nameHi: 'गुणत्रय विभाग योग',
    totalItems: 3,
    range: [54, 56],
  },
  {
    index: 15,
    name: 'Purushottama Yoga',
    nameGu: 'પુરુષોત્તમ યોગ',
    nameHi: 'पुरुषोत्तम योग',
    totalItems: 2,
    range: [57, 58],
  },
  {
    index: 16,
    name: 'Daivasura Sampad Vibhaga Yoga',
    nameGu: 'દૈવાસુર સંપદ વિભાગ યોગ',
    nameHi: 'दैवासुर संपद विभाग योग',
    totalItems: 2,
    range: [59, 60],
  },
  {
    index: 17,
    name: 'Shraddhatraya Vibhaga Yoga',
    nameGu: 'શ્રદ્ધાત્રય વિભાગ યોગ',
    nameHi: 'श्रद्धात्रय विभाग योग',
    totalItems: 3,
    range: [61, 63],
  },
  {
    index: 18,
    name: 'Moksha Sanyasa Yoga',
    nameGu: 'મોક્ષ સંન્યાસ યોગ',
    nameHi: 'मोक्ष संन्यास योग',
    totalItems: 8,
    range: [64, 71],
  },
];
