import type { Section } from '../types';

export const upanishadSections: Section[] = [
  {
    index: 1,
    name: 'Isha Upanishad',
    nameGu: 'ઈશ ઉપનિષદ',
    nameHi: 'ईश उपनिषद',
    totalItems: 2,
    range: [1, 2],
  },
  {
    index: 2,
    name: 'Kena Upanishad',
    nameGu: 'કેન ઉપનિષદ',
    nameHi: 'केन उपनिषद',
    totalItems: 2,
    range: [3, 4],
  },
  {
    index: 3,
    name: 'Katha Upanishad',
    nameGu: 'કઠ ઉપનિષદ',
    nameHi: 'कठ उपनिषद',
    totalItems: 5,
    range: [5, 9],
  },
  {
    index: 4,
    name: 'Prashna Upanishad',
    nameGu: 'પ્રશ્ન ઉપનિષદ',
    nameHi: 'प्रश्न उपनिषद',
    totalItems: 3,
    range: [10, 12],
  },
  {
    index: 5,
    name: 'Mundaka Upanishad',
    nameGu: 'મુંડક ઉપનિષદ',
    nameHi: 'मुण्डक उपनिषद',
    totalItems: 3,
    range: [13, 15],
  },
  {
    index: 6,
    name: 'Mandukya Upanishad',
    nameGu: 'માંડૂક્ય ઉપનિષદ',
    nameHi: 'माण्डूक्य उपनिषद',
    totalItems: 2,
    range: [16, 17],
  },
  {
    index: 7,
    name: 'Taittiriya Upanishad',
    nameGu: 'તૈત્તિરીય ઉપનિષદ',
    nameHi: 'तैत्तिरीय उपनिषद',
    totalItems: 3,
    range: [18, 20],
  },
  {
    index: 8,
    name: 'Aitareya Upanishad',
    nameGu: 'ઐતરેય ઉપનિષદ',
    nameHi: 'ऐतरेय उपनिषद',
    totalItems: 2,
    range: [21, 22],
  },
  {
    index: 9,
    name: 'Chandogya Upanishad',
    nameGu: 'છાંદોગ્ય ઉપનિષદ',
    nameHi: 'छान्दोग्य उपनिषद',
    totalItems: 10,
    range: [23, 32],
  },
  {
    index: 10,
    name: 'Brihadaranyaka Upanishad',
    nameGu: 'બૃહદારણ્યક ઉપનિષદ',
    nameHi: 'बृहदारण्यक उपनिषद',
    totalItems: 12,
    range: [33, 44],
  },
  {
    index: 11,
    name: 'Shvetashvatara Upanishad',
    nameGu: 'શ્વેતાશ્વતર ઉપનિષદ',
    nameHi: 'श्वेताश्वतर उपनिषद',
    totalItems: 4,
    range: [45, 48],
  },
];
